# -*- coding: utf-8 -*-
"""Hyperparameter_Tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OcyMpc8z6yVrZJrdf0_yNF2U5hnV-gVF
"""

import numpy as np
import pandas as pd

df  = pd.read_csv('Pima_Indians_Diabetes_Database.csv')
df.head()

df.corr()['Outcome']

"""We observe that BP and skin thickness do not impact outcome much"""

# Let's build a small model
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

X

#Since we are building a Neural Network , we need to first scale the input values
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled

X.shape

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.2, random_state = 42)

import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(32, input_dim = 8, activation  = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(loss = 'binary_crossentropy', optimizer = 'Adam', metrics = (['accuracy']))
model.fit(X_train, y_train, batch_size = 32, epochs = 100, validation_data = (X_test, y_test))

"""Here we need to decide the following hyperparameters ourselves:

1. Number of layers
2. Number of nodes in each layer
3. Activation function
4. Batch Size
5. Number of epochs
6. Loss function
7. Optimizer

It is like trial and error, but can be automated by a library known as **Keras Tuner**

It helps us select the best set of hyperparameters for the dataset for making the model.
"""

#1 Selecting the best optimizer
#first install keras tuner
!pip install -U keras-tuner

import kerastuner as kt

"""# Steps:
1. Make a function
2. Make a tuner object
3. Pass the function to the tuner object
"""

def build_model(hp): #A standard name of the function (build_model),
#hp = hyperparameter is an object of the hyperparameter class which is passed on to the build_model function
  #Build the model here
  model = Sequential()
  model.add(Dense(32, input_dim = 8, activation = 'relu'))
  model.add(Dense(1, activation = 'sigmoid'))
  model.compile(loss = 'binary_crossentropy', optimizer = hp.Choice('optimizer', values = ['adam', 'sgd', 'rmsprop', 'adadelta']), metrics = (['accuracy']) )
  # Here, we need to select the optimizer from a list
  # Syntax Signature" optimizer = hp.choice(pass a string say'optimizer', after the comma provide a LIST ['adam', 'sgd', 'rmsprop', 'adadelta'] for 'values' parameter)
  # This code will build 4 models, each witha different optimizer provided from the list

  return model

tuner = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 5)
# Try 5 different hyperparameter combinations
# Making an object. The first paramter is the function, 2nd one is the objective, i.e. which thing to reduce/increase, automatically detected
# The tuner will evaluate the combinations using the validation accuracy (val_accuracy) and return the best-performing configuration.

# Start the hyperparameter search process:
# The tuner will try different combinations of hyperparameters and train the model multiple times.

# X_train, y_train: Training data (features and labels) used to train the model.
# epochs=5: The model will train for 5 epochs (iterations over the training data) for each hyperparameter combination.
# validation_data=(X_test, y_test): Validation data used to evaluate the model performance after each epoch.
# The tuner will use these validation results to determine the best hyperparameter combination.
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test), verbose=1)

tuner.results_summary()

tuner.get_best_hyperparameters()[0].values

model = tuner.get_best_models(num_models = 1)[0]

model.summary()

model.fit(X_train, y_train, batch_size = 32, initial_epoch = 6, epochs = 100, validation_data = (X_test, y_test))
#Since 5 epochs par already trained on best model, so we would like to retain the information

"""Here accuracy around 75%, SEE val_accuracy

#2. Hyperparameter tuning of number of nodes in a given layer
"""

def build_model(hp):
  model = Sequential()
  units = hp.Int('units', min_value = 8, max_value = 128, step = 8) # build multiple models, can take any step size
  #First model with 8 neurons in hidden layer, 2nd with 16, till 128 and RETURNS THE MODEL WITH THE BEST RESULTS
  model.add(Dense(units = units, input_dim = 8, activation = 'relu'))
  model.add(Dense(1, activation = 'sigmoid'))
  model.compile(loss = 'binary_crossentropy', optimizer = hp.Choice('optimizer', values = ['adam', 'sgd', 'rmsprop', 'adadelta']), metrics = (['accuracy']))
  return model  #total 16 X 4 = 64 models

tuner2 = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 5, directory = 'new_dir') # It will pick the already stored model if dir not added

tuner2.search(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

tuner2.results_summary()

tuner2.get_best_hyperparameters()[0].values

model = tuner2.get_best_models(num_models = 1)[0]

model.fit(X_train, y_train, batch_size = 32, initial_epoch = 6, epochs = 100, validation_data = (X_test, y_test))

"""Accuracy here = 75%

# 3. Tuning number of layers
"""

def build_model(hp):
  model = Sequential()
  model.add(Dense(72, input_dim = 8, activation = 'relu')) # first hidden layer
  for i in range(hp.Int('num_layers', min_value = 1, max_value = 10)): # it is two loops actually
    model.add(Dense(72, activation = 'relu')) # jitne bhi layers bane by hyperparameter tuning, for each layer 72 nodes, can change it also

  model.add(Dense(1, activation = 'sigmoid'))

  model.compile(loss = 'binary_crossentropy', optimizer = 'rmsprop', metrics = ['accuracy'])

  return model

tuner3 = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 3, directory = 'new_directory')

tuner3.search(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

tuner3.get_best_hyperparameters()[0].values

model = tuner3.get_best_models(num_models = 1)[0]

model.fit(X_train, y_train, batch_size = 32, initial_epoch = 6, epochs = 100, validation_data = (X_test, y_test))

"""Here, Accuracy = 74%

# FINAL COMBINATION MODEL
"""

from keras.layers import Dropout
def build_model(hp):
    model = Sequential()

    # Number of hidden layers (dynamic based on hyperparameter)
    num_layers = hp.Int('num_layers', min_value=1, max_value=10)

    # Adding layers dynamically
    for i in range(num_layers):
        # If it's the first layer, specify input_dim
        if i == 0:
            model.add(Dense(
                hp.Int('units' + str(i), min_value=8, max_value=128, step=8),  # Units per layer
                activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid']),  # Activation function
                input_dim=8  # Input dimension for the first layer (assuming 8 features)
            ))
            model.add(Dropout(hp.Choice('dropout' + str(i), values = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))
        else:  # For subsequent layers, no need for input_dim
            model.add(Dense(
                hp.Int('units' + str(i), min_value=8, max_value=128, step=8),  # Units per layer
                activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid'])  # Activation function
            ))
            model.add(Dropout(hp.Choice('dropout' + str(i), values = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))

    # Add output layer
    model.add(Dense(1, activation='sigmoid'))  # Output layer for binary classification

    # Compile the model with dynamic optimizer choice
    model.compile(
        loss='binary_crossentropy',
        optimizer=hp.Choice('optimizer', values=['adam', 'rmsprop', 'sgd', 'nadam', 'adadelta']),
        metrics=['accuracy']
    )

    return model

tuner_final = kt.RandomSearch(build_model,
                              objective = 'val_accuracy',
                              max_trials = 5,
                              directory = 'Final_dir',
                              project_name = 'Final_Project')

tuner_final.search(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

tuner_final.get_best_hyperparameters()[0].values

model_final = tuner_final.get_best_models(num_models = 1)[0]
model_final.fit(X_train, y_train, epochs = 200, initial_epoch = 5, validation_data = (X_test, y_test))

